version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore(deps):"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(deps):"

  - package-ecosystem: "pub"
    directory: "/mobile/balcony_guard_app"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "flutter"
    commit-message:
      prefix: "chore(deps):"
